# Generated by Django 4.2.4 on 2023-08-12 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0002_veiculo_imagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={},
        ),
    ]
