# Generated by Django 4.2.4 on 2023-08-12 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_veiculo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório"},
        ),
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "Cores"},
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículo"},
        ),
    ]
