# Generated by Django 4.2.4 on 2023-08-12 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_alter_categoria_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório"},
        ),
    ]
