# Generated by Django 4.2.4 on 2023-08-12 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_alter_acessorio_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marca",
            name="nacionalidade",
        ),
    ]
