# Generated by Django 4.2.4 on 2023-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0005_remove_marca_nacionalidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorios",
            field=models.ManyToManyField(
                related_name="veiculos", to="garagem.acessorio"
            ),
        ),
    ]
