# Generated by Django 4.2.4 on 2023-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0017_veiculo_modelo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
