# Generated by Django 4.2.4 on 2023-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0023_remove_veiculo_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
