# Generated by Django 4.2.4 on 2023-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0024_veiculo_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
