# Generated by Django 4.2.4 on 2023-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0025_alter_veiculo_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(default="", max_length=100),
        ),
    ]
