# Generated by Django 4.2.4 on 2023-08-12 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0026_alter_veiculo_descricao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={},
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Acessório"},
        ),
    ]
